import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ether Coffee</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex items-center justify-center h-screen w-full text-3xl'>
        <h1>Gm ☕️</h1>
      </div>
    </div>
  )
}
